### ISSUE TITLE
ldid replaces entitlements instead of merging when signing a directory

### ISSUE THREAD

**Issue by superrnovae** [ProcursusTeam/ldid#18]
Example:

`ldid -S -M -Kcert.p12 <mach-o>` will resign the file and merge existing entitlements with empty ones.
 
 But when used on a directory:
 
`ldid -S -M -Kcert.p12 <name.app>` will resign all mach-o and replace their entitlements with empty ones.

and -s flag doesn't work on a directory, so there is no way to deep sign like with codesign.
   
**ldid version:** v2.1.5-procursus4
**os:** linux, macOS

**Comment by Teutates** [comment]
Confirmed  `ldid  -Kcert.p12 -Sent.plist -M <name.app>` and `ldid  -Kcert.p12 -s <name.app>` both perform as expected with ldid v2.1.5-procursus5.
