### ISSUE TITLE
ldid strips entitlements of stray binaries even when using -s

### ISSUE THREAD

**Issue by opa334** [ProcursusTeam/ldid#24]
When signing an app bundle and you have a stray binary inside it, ldid correctly resigns it but for whatever reason that binary looses it's entitlements. Works fine for main binary / app plugin binaries.

**Comment by CRKatri** [comment]
If signed with -Sent.xml, do the new entitlements get applied? Or does it get signed with no entitlements?

**Comment by opa334** [comment]
> If signed with -Sent.xml, do the new entitlements get applied? Or does it get signed with no entitlements?

It gets signed with no entitlements

**Comment by opa334** [comment]
Fix works
