### ISSUE TITLE
ldid -K not working?

### ISSUE THREAD

**Issue by LIJI32** [ProcursusTeam/ldid#26]
I'm probably doing something wrong, but no matter how I uses the `-K` option I get a different kind of error. Some p12 file sign successfully but fail to verify with `codesign -v` (`CSSMERR_TP_NOT_TRUSTED`), some give various parsing errors (`ldid: An error occured while parsing: error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure`, `ldid: An error occursed while parsing the certificate: error:00000000:lib(0):func(0):reason(0)`). Additionally, it seems to keep asking for a password despite never having set one.

I tried with both a self-signed code-signing certificate I exported from Keychain Access as p12, an iOS developer certificate similarly exported, and a p12 certificate generated by AltSign.

What am I possibly doing wrong?

I attached the p12 files I'm trying to sign with (I'm aware they contain private keys).
[p12.zip](https://github.com/ProcursusTeam/ldid/files/9997714/p12.zip)

**Comment by Teutates** [comment]
Thank you for the report. I'll investigate this ASAP and get back with any further clarification needed.

**Comment by LIJI32** [comment]
It seems that the root cause was that I was accidentally mixing and matching the new and old Apple root developer certificates. I'll leave this open in case you want to make error handling a bit nicer.
