### ISSUE TITLE
Can you build ldid for tvOS?

### ISSUE THREAD

**Issue by miosx** [ProcursusTeam/ldid#35]
Can you build ldid for tvOS?
Thanks.

**Comment by miosx** [comment]
Thanks. I tried to compile ldid for tvOS. When I ran it, I got an error. Can you make a release for tvOS? Just like iOS, I can use it directly.
`
ldid exited with status 1
ldid: An error occured while parsing: error:12800067:DSO support routines::could not load the shared library
`

**Comment by CRKatri** [comment]
This looks like a OpenSSL error. Try compiling it with static modules

**Comment by miosx** [comment]
Ok, Thanks
