### ISSUE TITLE
Can't build with latest libplist

### ISSUE THREAD

**Issue by Un1q32** [ProcursusTeam/ldid#40]
https://github.com/libimobiledevice/libplist/releases/tag/2.5.0 changed parts of the API to use `uint8_t *` instead of `char *` which causes ldid to fail to compile

**Comment by TheRealKeto** [comment]
[libplist 2.6.0](https://github.com/libimobiledevice/libplist/releases/tag/2.6.0) reverts any breaking changes previously introduced. This issue can be closed.
