### ISSUE TITLE
Entitlement causes ldid to hang

### ISSUE THREAD

**Issue by verygenericname** [ProcursusTeam/ldid#41]
The com.apple.trial.status.deployment-environment.allow entitlement, found on Preferences, causes ldid to hang and sometimes fail. It is an array with integers residing in the array. attached is a plist that has the entitlement on it
[ent.txt](https://github.com/user-attachments/files/16531735/ent.txt)

**Comment by TheRealKeto** [comment]
[`f38a095`](https://github.com/ProcursusTeam/ldid/commit/f38a095aa0cc721c40050cb074116c153608a11b) has addressed this issue. Sadly, no new release has been made. Please use the latest commit or wait until a new release.

This issue can be closed.

**Comment by verygenericname** [comment]
Thanks
