### ISSUE TITLE
Lacks a15 support

### ISSUE THREAD

**Issue by Cryptiiiic** [ProcursusTeam/ldid#5]
I tried using ldid, impactor, and zsign on my a15 device. All apps seem to install fine but when opened, just crash. As soon as I use the apple codesign command with the same certs, it can be installed and the app runs fine without crashing. 
Here is a diff between ldid and apple codesign:
![image](https://user-images.githubusercontent.com/27748705/137806415-4e1a776b-58b1-4e44-be10-cf9995313449.png)

It seems to not be including resources such as lproj's info.plist's, etc. Its lacking the Authority despite providing the same authority cert.

**Comment by Diatrus** [comment]
Is this the very latest ldid from the releases?

**Comment by CRKatri** [comment]
Are you sure that it's v2.1.5-procursus2? I though that I had fixed that...

**Comment by Cryptiiiic** [comment]
@CRKatri 
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/27748705/137808206-11ea1046-aa90-4ae9-b9df-89ef790f2031.png">

**Comment by Cryptiiiic** [comment]
Bump :(

**Comment by CRKatri** [comment]
I did a `git bisect` between `v2.1.5` and `v2.1.5-procursus2` and it seems that the `Authority` stopped working with commit `294b81953c0801212a7f0927133e3c43ca231ab3`.

**Comment by CRKatri** [comment]
I had already shared this with you, but just putting here for posterity.

Try generating a key.p12 with the full cert chain using these command
```
curl -sL https://www.apple.com/appleca/AppleIncRootCertificate.cer | openssl x509 -inform der > Apple.pem
curl -sL https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer | openssl x509 -inform der >> Apple.pem
openssl pkcs12 -in Certificates.p12 -nocerts -nodes | openssl rsa > development.key
openssl pkcs12 -in Certificates.p12 -clcerts -nokeys -out cert.pem
openssl pkcs12 -export -out key.p12 -inkey development.key -in cert.pem -certfile Apple.pem
```

**Comment by CRKatri** [comment]
Try using a key generated with the above message and 1adec13

**Comment by Cryptiiiic** [comment]
![image](https://user-images.githubusercontent.com/27748705/177659931-59e123e9-2456-4157-81c7-c8fe938dbfdf.png)
Fix confirmed! closing.
